package com.users.repositories;

import java.util.List;
import org.springframework.data.repository.CrudRepository;
import com.users.beans.Contact;



public interface ContactRepository extends CrudRepository<Contact, Long>{

	Contact findByUserIdAndId(long userId, long id); //finds by userId and autogenerated id for contact.java
	
//	List<Contact> findByUserIdAndLastName(long userId, String lastName); //finds by userId and last name

//	List<Contact> findByUserIdAndEmail(long userId, String email); //finds by userId and email

	List<Contact> findAllByUserIdOrderByFirstNameAscLastNameAsc(long userId); //finds all Contacts by userId, first name ascending and last name ascending

	List<Contact> findByLastNameOrFirstNameOrEmailOrTwitterHandleOrFacebookUrlIgnoreCase(
			String lastName, String firstName, String email, String twitterHandle,
			String facebookUrl);//this allows us to find a user by using any parameter

	
//	List<Contact> findByLastName(String lastName);
//
//	List<Contact> findByEmail(String email);
//
//	List<Contact> findAllByOrderByFirstNameAscLastNameAsc(); //finds All Contacts by First name, Last Name Ascending https://www.petrikainulainen.net/programming/spring-framework/spring-data-jpa-tutorial-part-six-sorting/
}
